import pyautogui as py
py.press('win')
py.write('chrome')
py.press('enter')
py.sleep(2)
py.write('senai americana')
py.press('enter')
py.sleep(3)
py.click(238,459,button='left')
py.sleep(4)
py.click(1331,781,button='left')
py.sleep(3)
py.click(185,565,button='left')
py.sleep(1)
py.click(213,492,button='left')
py.write('Python')
py.press('enter')
py.sleep(1.8)
py.vscroll(-200)